DROP DATABASE IF EXISTS ATLAS;
CREATE DATABASE ATLAS;
USE ATLAS;

CREATE TABLE BIBLIOTECA (
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(40) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE SESSAO (
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    ID_BIBLIOTECA INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(ID_BIBLIOTECA) REFERENCES BIBLIOTECA(ID)
);

CREATE TABLE LIVRO (
	ID INT NOT NULL AUTO_INCREMENT,
    ID_SESSAO INT NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    AUTOR VARCHAR(40) NOT NULL,
    EDITORA VARCHAR(30) NOT NULL,
    EDICAO INT NOT NULL,
    ALUGADO BOOLEAN NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(ID_SESSAO) REFERENCES SESSAO(ID)
);

CREATE TABLE USUARIO (
	ID INT NOT NULL AUTO_INCREMENT,
    ID_BIBLIOTECA INT NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(40) NOT NULL,
    TIPO INT NOT NULL,
    LOGIN VARCHAR(20) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    RUA VARCHAR(40) NOT NULL,
    NUMERORUA INT NOT NULL,
    BAIRO VARCHAR(25) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    DDDFIXO VARCHAR(2),
	FONEFIXO VARCHAR(8),
    DDDMOVEL VARCHAR(2),
    FONEMOVEL VARCHAR(9),
    PRIMARY KEY(ID),
    FOREIGN KEY(ID_BIBLIOTECA) REFERENCES BIBLIOTECA(ID)
);

CREATE TABLE ALUGUEL (
	ID INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    DATALOCACAO DATE NOT NULL,
    DEVOLUCAOPREVISTA DATE NOT NULL,
    DEVOLUCAOEFETIVA DATE NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE ALUGUEL_LIVRO (
	ID INT NOT NULL AUTO_INCREMENT,
    ID_ALUGUEL INT NOT NULL,
    ID_LIVRO INT NOT NULL,
    PRIMARY KEY(ID, ID_ALUGUEL, ID_LIVRO),
    FOREIGN KEY(ID_ALUGUEL) REFERENCES ALUGUEL(ID),
    FOREIGN KEY(ID_LIVRO) REFERENCES LIVRO(ID)
);
